[package]
name = "lua51-deserializer"
authors = ["Amit Bashan <amit.bashan@icloud.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "*"
num-traits = "*"
num-derive = "*"
either = "*"
enum-as-inner = "*"